### PR TITLE
Giant Update

### PR DESCRIPTION
**Pull request by PowerMacFan**
This is a **MASSIVE** update.
The better version of the pull request #34 I made earlier.  
This pull request adds a new program named "box" (I also made a wiki page for it) and some changes with some text in the programs "Raspberry Pi Detector" and "areas" and changes to the contribution guidelines.  
Here is the full list of changed stuff.  

Added a page for the "box" program in this pull request.  
Changed some text in the program "Areas".  
Added a program called "box"
Changed text in the program "Raspberry Pi Detector".  
Added the "box" programs wiki page to the page index.

### CODE REVIEW

**Comment by jayam04** [comment]
What help?

**Comment by jayam04** [comment]
Are you using Slack?

**Comment by jayam04** [comment]
Join me on Slack – it’s a faster, simpler way to work. Sign up here, from any device: https://join.slack.com/t/coding-workspace-corp/shared_invite/zt-zqg9hy8y-OhKjQBQx8HFPMoZWKG4nAA

**Comment by PowerMacFan** [comment]
> What help?  

just some help on making sure everything looks good in this pull

**Comment by PowerMacFan** [comment]
> Join me on Slack – it’s a faster, simpler way to work. Sign up here, from any device: https://join.slack.com/t/coding-workspace-corp/shared_invite/zt-zqg9hy8y-OhKjQBQx8HFPMoZWKG4nAA

i might be able to make a account

**Comment by jayam04** [comment]
> > Join me on Slack – it’s a faster, simpler way to work. Sign up here, from any device: https://join.slack.com/t/coding-workspace-corp/shared_invite/zt-zqg9hy8y-OhKjQBQx8HFPMoZWKG4nAA
> 
> i might be able to make a account

It’s ok if you can’t , as I am only member it won’t worth for you if you aren’t interested.

**Comment by PowerMacFan** [comment]
> > > Join me on Slack – it’s a faster, simpler way to work. Sign up here, from any device: https://join.slack.com/t/coding-workspace-corp/shared_invite/zt-zqg9hy8y-OhKjQBQx8HFPMoZWKG4nAA
> > 
> > 
> > i might be able to make a account
> 
> It’s ok if you can’t , as I am only member it won’t worth for you if you aren’t interested.

ok, also should we add anything else before merging?

**Comment by jayam04** [comment]
I think we should merge we would make another branch making it better and committing after 2 to 3 weeks.

**Comment by jayam04** [comment]
We would need to work on wiki

**Comment by PowerMacFan** [comment]
Sounds good, also how about you do a review?

**Comment by PowerMacFan** [comment]
Do you mind if I merge?

**Comment by jayam04** [comment]
I don’t know how to review. 
Yes just merge it now.

**Review by jayam04 — APPROVED** [review]

**Pull request merged**
